---
# tasks file for mysqldb
- name: Start service mysql, if not started
  service:
    name: mysql
    state: started

- name: Create a new database with name 'employees'
  mysql_db:
    name: employees
    state: present

- name: Copy database dump file
  copy:
    src: employees.sql.tar.bz2
    dest: /tmp
- name: Restore database
  mysql_db:
    name: my_db
    state: import
    target: /tmp/employees.sql.tar.bz2
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Dump all databases to hostname.sql
  mysql_db:
    state: dump
    name: all
    target: /tmp/employees.sql
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
  mysql_db:
    state: import
    name: all
    target: /tmp/employees.sql
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
